### PR TITLE
Pull ADRs from remote (public) git repositories

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

Publishes architecture decision records related to software systems by pulling them across from other repositories.

Any software system defining their ADR location with

```kt
ADRSource("https://github.com/ministryofjustice/reponame").addTo(this)
```

will be automatically cloned during the build and parsed for ADRs.

ℹ️ For now, the code expects `adr-tools` specific structure: in the cloned repository, a `doc/adr` folder structure has to exist.

## What is the intent behind these changes?

1. To allow clearer code ownership; please see discussion in #90 
2. To create the foundation for further processing: we can pull a lot of detail from container app repos :)

## Where did the decisions go?

https://github.com/ministryofjustice/hmpps-interventions-docs

### CODE REVIEW

**Review by mxco86 — APPROVED** [review]
LGTM

**Review by spikeheap — APPROVED** [review]
:+1: to removing the ADRs from this repo and introducing metadata to link out to something owned/maintained by the team.

Is there value in having these ADRs in our central Structurizr account? I'd hope to see the account expose HMPPS-wide architectural decisions, but I'm not sure of the value of pushing teams to host their ADRs in a single place, particularly because we use them for varying levels from "this is how we write a commit message" to "this is how we'll architect a complex interaction".

I'm not tied to either approach, but if we're _not_ deciding to homogenise the ADR output across all teams we _may_ end up with the Structurizr workspace being HMPPS high level + interventions 🤷‍♂️.

**Comment by sldblog** [comment]
Good point @spikeheap, it's an assumption from my end. 🤔 I was thinking about:

----

We need to support the visibility of all system-related ADRs in a single place to meet the following user needs:

- Teams and architects able to discover related decisions in the wider organisation
- Make it easier to publish the contents with colours and badges
- Reduce manual maintenance on wiki pages concerned with "these are all the ADRs in our unit"

----

Does that make sense?

**Comment by spikeheap** [comment]
:+1: 🙇 @sldblog do we _need_ to have all ADRs in a single place? I agree with the premise for system/high-level ADRs (e.g. how do we manage secrets), but every project I've seen has mixed these with smaller/lower-level ones (e.g. renaming `master` to `main`.

I wonder what success looks like for ADRs? I tend to promote many, small ADRs to get into the habit of writing them regularly, but it makes the register less useful for other teams than one that contains fewer, big decisions. Being able to search over all of them _sounds_ good for discoverability, but I guess I'm questioning whether a TA/Dev/etc. would ever browse a single source across multiple projects?  Could we tag them somehow or use metadata to differentiate them?

Thinking about if/how we can sell it to other teams (which I think is key to it being a central, authoritative resource), what incentive would we have for individual teams to use this (rather than Google Drive, Confluence)? If they're already using Markdown it's pretty trivial 🥳.

Either way, not blocking this, we should grab a coffee to chat about it sometime!

**Comment by sldblog** [comment]
@spikeheap 🙇‍♂️ Thank you! Let's catch up. I'm thinking about visibility, identifying recurring patterns, easy TOC generation as potential topics.

**Pull request merged**
