### PR TITLE
Add "offender management in custody" container view

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

Adds a new container view, focussed on offender management in custody. The model was already there but I didn't export a view.

Naming and placement of elements in the model were also corrected.

**Result**
structurizr-55488-omic-container

## What is the intent behind these changes?

To be able to present an up-to-date OMiC container context directly via image links.

### CODE REVIEW

**Comment by sldblog** [comment]
cc @ollietreend

**Comment by sldblog** [comment]
cc @ministryofjustice/offender-management

The aim of this diagram is to visualise to technical people how `offender-management-allocation-manager` interacts with other services and who are its users. (Ideally it could be added to the readme of the github repo.)

Do you have any suggestions/feedback?

**Comment by ollietreend** [comment]
@sldblog

### Prison API

> "polls service users currently in the logged in user's prison from"

I think there's a typo – should this be "**pulls** service users..."?

### Prison Offender Search API

We do also consume data from the [Prison Offender Search API](https://github.com/ministryofjustice/prisoner-offender-search).

Specifically, we use this API to determine the 'recall' status of a given service user (offender). This supplements the data that we already receive from the Prison API.

Maybe something like this would make sense:

> "pulls the 'recall' status of service users from"

### HMPPS Auth

Not sure if it's also worth mentioning that our users authenticate to MOIC with HMPPS Auth.

### Community API

We aren't using this right now. But will probably need your help to update this diagram when we do start using it! 🙂

**Comment by sldblog** [comment]
Thank you @ollietreend 🙇 
These changes are now in 5140d9b067b6fd76da782cc7f64e52efe2ae6ffe

**Review by garethmdavies — APPROVED** [review]
LGTM

**Comment by sldblog** [comment]
Thank you @garethmdavies 🙇 🏆 🎩

**Pull request merged**
